name: "❓ Post a Question"
description: Got a question to ask? Use this template to share with us.
labels:
 - question
 
body:
  - type: textarea
    attributes:
      label: What do you want to ask?
      placeholder: "[Question]: How do I..."
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Please describe your question
    validations:
      required: true